name: Merge Blocker

on: [pull_request]

permissions: {}

jobs:
  prepare-environment:
    name: Setup Node.js + npm, and install
    runs-on: ubuntu-latest
    outputs:
      node-version: '22.17.0'
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install specific npm version
        run: npm install --audit false --fund false -g npm@11.4.2

  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: prepare-environment
    steps:
      - uses: actions/checkout@v4
      - name: Audit Check
        run: npm audit

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: prepare-environment
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --audit false --fund false
      - name: ESLint Check
        run: npm run lintOnly

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: prepare-environment
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --audit false --fund false
      - name: Prettier Check
        run: npm run prettierCheck

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    needs: prepare-environment
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --audit false --fund false
      - name: TypeScript Check
        run: npm run typecheck
